services:
  project_web:
    image: nginx
    ports:
      - "8077:80"
    volumes:
      - ../:/azure_project
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  project_php:
    image: php:fpm
    volumes:
      - ../:/azure_project
  project_db:
    image: mariadb
#    ports:
#      - "3306:3306"
    volumes:
      - ../:/azure_project
    environment:
      MARIADB_ROOT_PASSWORD: 123456